name: Publish

on:
  push:
    branches: [ master ]
    # ignore commits made after publishing
    tags-ignore: 
      - v*

jobs:
  publish:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    # Install
    - name: Install
      uses: bahmutov/npm-install@v1.1.0
    
    - name: Publish
      run: npm run publish
