name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Install
    - name: Install
      uses: bahmutov/npm-install@v1.1.0
    
    - name: Build
      run: npm run build
    
    - name: Publish
      run: npm run publish
