name: Publish

on:
  push:
    branches: [ master ]
    # ignore commits made after publishing
    tags-ignore: 
      - v*

jobs:
  publish:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install
      uses: bahmutov/npm-install@v1.1.0
    
    - name: Install SKPM
      run: npm i -g skpm
    
    - name: Login
      run: skpm login ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish
      run: npm run publish
